### ISSUE TITLE
Listing cluster applications not working

### ISSUE THREAD

**Issue by Jose-CF** [Azure/service-fabric-cli#38]
I used to use Azure CLI 2.0 and was working fine.
Last update dropped Service Fabric.

I just installed sfctl. I can select my cluster as previously, seems normal:
`sfctl cluster select --endpoint http://cf-imageservice-test.southeastasia.cloudapp.azure.com:19080`

Although no output from this command. 

When I issue: 
`sfctl application list`

I get the following error:

```
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.5/dist-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.5/dist-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.5/dist-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 3409, in get_application_info_list
    raise models.FabricErrorException(self._deserialize, response)
azure.servicefabric.models.fabric_error.FabricErrorException: Operation returned an invalid status code 'Bad Request'

```

Any workarounds?

**Comment by samedder** [comment]
What's the runtime version of your Service Fabric cluster? Can you also check what version of sfctl you're using? you can do this with `pip show sfctl`.

**Comment by Jose-CF** [comment]
I found the problem.... the problem is that the set of GET parameters the servicefabric package was issuing... were correct... but only correct from version 6.x of Service Fabric cluster. Actually that was only very recently released.

So the version my cluster had did not recognize the parameters....

This is a terrible issue since most people did not upgrade their clusters yet as 6.x was only released recently. But Azure CLI 2.0 already dropped service fabric so many people will start using sfctl by now and will experience this issue.

**Comment by linggengmsft** [comment]
@Jose-CF , could you try install the older version of sfctl which works with previous clusters?

pip uninstall sfctl
pip install sfctl==1.1.0
