### ISSUE TITLE
sfctl service update --load-metrics json argument format

### ISSUE THREAD

**Issue by serbrech** [Azure/service-fabric-cli#46]
The doc states 

--load-metrics | JSON encoded list of metrics used when load balancing services across           nodes.
-- | --  

 I looked in the tests to maybe find an example, but they use the python method directly so, it does not give a CLI example : 

https://github.com/Azure/service-fabric-cli/blob/89265b7c19f503956f9a23490352086c38cf226f/src/sfctl/tests/service_test.py#L44

And following this example using --parameters [passing json to the sfctl cli](https://docs.microsoft.com/en-us/azure/service-fabric/scripts/sfctl-upgrade-application), I tried : 

```shell
sfctl service update --service-id ServiceManifestChanges/StatefulSvc --load-metrics "[{\"name\":
\"Test\", \"default_primary_load\":100, \"default_secondary_load\"}]" --stateful
```

But I also tried : 
```
sfctl service update --service-id ServiceManifestChanges/StatefulSvc --stateful  --load-metrics "[{'name':
'Test', 'default_primary_load':100, 'default_secondary_load':100}]" 

sfctl service update --service-id ServiceManifestChanges/StatefulSvc --stateful --load-metrics "[{name:
Test, default_primary_load:100, default_secondary_load:100}]"

```

They all fail with the same unhelpful error message :   

```python
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python2.7/dist-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python2.7/dist-packages/sfctl/custom_service.py", line 438, in update
    metric_desc = parse_load_metrics(load_metrics)
  File "/usr/local/lib/python2.7/dist-packages/sfctl/custom_service.py", line 36, in parse_load_metrics
    l_name = l.get('name', None)
AttributeError: 'str' object has no attribute 'get'
 ```    

So, it cannot parse the parameter. what is the expected format ?

**Comment by serbrech** [comment]
Looking at https://github.com/Azure/service-fabric-cli/blob/89265b7c19f503956f9a23490352086c38cf226f/src/sfctl/params.py#L52

Does this mean the `update` verb does not support the --load-metrics argument as it's not listed in the arg_context?

**Comment by samedder** [comment]
This is an issue it looks like with how the JSON string is parsed. There's a fix in PR now.
