### ISSUE TITLE
sfctl application upload throws FABRIC_E_SERVICE_DOES_NOT_EXIST

### ISSUE THREAD

**Issue by joakimhew** [Azure/service-fabric-cli#51]
**System info:**
Windows 10 build 15063
Service fabric runtime 6.0.219.9494
Service fabric SDK 2.8.219.9494
sfctl 3.0.0

**Issue**
I am trying to use the `application upload` option in sfctl for a .NET core project in the following manner:
`sfctl application upload --path CounterServiceApplication --show-progress`

This is found from the sample at [Azure-Samples](https://github.com/Azure-Samples/service-fabric-dotnet-core-getting-started/blob/master/Services/CounterService/install.sh#L19) but has thrown the error with every application I've tried.

The command will always result in throwing the following error:
`requests.exceptions.HTTPError: 404 Client Error: FABRIC_E_SERVICE_DOES_NOT_EXIST for url: http://192.168.0.57:19080/ImageStore/CounterServiceApplication/ApplicationManifest.xml?api-version=3.0-preview`

The full HTTP PUT request is:

**HEADERS**
PUT http://192.168.0.57:19080/ImageStore/CounterServiceApplication/ApplicationManifest.xml?api-version=3.0-preview HTTP/1.1
Host: 192.168.0.57:19080
User-Agent: python-requests/2.18.4
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 2424

**BODY**
```XML
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest ApplicationTypeName="CounterServiceApplicationType"
                     ApplicationTypeVersion="1.0.0"
                     xmlns="http://schemas.microsoft.com/2011/01/fabric"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Parameters>
    <Parameter Name="CounterService_MinReplicaSetSize" DefaultValue="3" />
    <Parameter Name="CounterService_PartitionCount" DefaultValue="1" />
    <Parameter Name="CounterService_TargetReplicaSetSize" DefaultValue="3" />
    <Parameter Name="CounterServiceWebService_InstanceCount" DefaultValue="-1" />
  </Parameters>
  <!-- Import the ServiceManifest from the ServicePackage. The ServiceManifestName and ServiceManifestVersion
       should match the Name and Version attributes of the ServiceManifest element defined in the
       ServiceManifest.xml file. -->
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="CounterServicePkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
  </ServiceManifestImport>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="CounterServiceWebServicePkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
  </ServiceManifestImport>
  <DefaultServices>
    <!-- The section below creates instances of service types, when an instance of this
         application type is created. You can also create one or more instances of service type using the
         ServiceFabric PowerShell module.

         The attribute ServiceTypeName below must match the name defined in the imported ServiceManifest.xml file. -->
    <Service Name="CounterService">
      <StatefulService ServiceTypeName="CounterServiceType" TargetReplicaSetSize="[CounterService_TargetReplicaSetSize]" MinReplicaSetSize="[CounterService_MinReplicaSetSize]">
        <UniformInt64Partition PartitionCount="[CounterService_PartitionCount]" LowKey="-9223372036854775808" HighKey="9223372036854775807" />
      </StatefulService>
    </Service>
    <Service Name="CounterServiceWebService">
      <StatelessService ServiceTypeName="CounterServiceWebServiceType" InstanceCount="[CounterServiceWebService_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
</ApplicationManifest>
```

**Comment by samedder** [comment]
This appears to be a bug in the way the API version string is specified in the CLI.

**Comment by jblackburn21** [comment]
I was running into the same issue when trying to deploy to a local cluster, and was able to run it successfully by using the file image store:

sfctl application upload --path CounterServiceApplication --imagestore-string "file:/mnt/c/SfDevCluster/Data/ImageStoreShare"

The local cluster doesn't appear to have the ImageStore system service running

**Comment by iyyappam** [comment]
I'll take a look.

**Comment by iyyappam** [comment]
I believe that you have setup a local cluster and was trying to upload without explicitly specifying imagestore_string as parameter. As @jblackburn21 mentioned, image store service is not run on the local cluster and you would get FABRIC_E_SERVICE_DOES_NOT_EXIST error. To fix it, provide --imagestore_string parameter for your local cluster.  Please let us know if you get this error for any other case.

**Comment by joakimhew** [comment]
@iyyappam Alright that explains it, just confirmed that the cluster running locally in windows has a ImageStoreConnectionString of "file:".. instead of "fabric:.."

I'm on a Mac and when I run a local cluster using the service fabric vagrant image, the `ImageStoreConnectionString` is "fabric:...". In this case, sfctl application upload works without explicitly providing the imagestore_string parameter.

Is the ImageStoreConnectionString parameter documented anywhere?

Thanks for the help 👍

**Comment by iyyappam** [comment]
You are welcome. 

You can read more about ImageStoreConnectionString here.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-image-store-connection-string

**Comment by jcannata** [comment]
I am running into this same issue when trying to issue a 'store delete' command on a standalone cluster. However, in this case there is no option for --imagestore-string. Any hints as to how I might specify the correct image store connection string?

**Comment by iyyappam** [comment]
Unfortunately there is no way to do it currently for the store delete when using local cluster. I'll file a bug on this.
