### ISSUE TITLE
Console output is not readable from POSH in default colour scheme

### ISSUE THREAD

**Issue by kkorsakov** [Azure/service-fabric-cli#56]
sfctl prints error output in red and POSH has blue background. Text is completely unrecognizable. 

![image](https://user-images.githubusercontent.com/966331/32875587-36d46f9c-cab2-11e7-8f0b-011c64dee8f7.png)

**Comment by samedder** [comment]
Won't fix, sorry.

As a workaround you can change the background colour of your PowerShell window to be black or grey, or another contrasting colour.
