### ISSUE TITLE
"--no-verify" option doesn't work

### ISSUE THREAD

**Issue by rganz** [Azure/service-fabric-cli#65]
When I try to connect to my cluster on Azure using sfctl I get an error. I assume it is because of the self-signed certificates.

```
sfctl cluster select --endpoint https://cluster.region.cloudapp.azure.com:19080 --pem ./cluster.pem
Error occurred in request., SSLError: HTTPSConnectionPool(host='cluster.region.cloudapp.azure.com', port=19080): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
```

Then I pass the `--no-verify` option, I just get another error that this is not recomended. But then nothing happens.
```
sfctl cluster select --endpoint https://cluster.region.cloudapp.azure.com:19080 --pem ./cluster.pem --no-verify
c:\program files\python36\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

I reach the SF Explorer page with Chrome without any problems.
curl of `https://cluster.region.cloudapp.azure.com:19080` works als well, when I pass the certificate and the `--insecure` option.

sfctl version is 3.0.0.
sf runtime version is 6.1.456.9494
hosting on Azure

**Comment by samedder** [comment]
@rganz what doesn't work? Can you run `sfctl node list`? The warning will always be displayed, it's a reminder that you're performing an insecure operation.

**Comment by rganz** [comment]
Oh, that works. I was expecting some feedback to `connect` like a "sucessfully connected".

**Comment by paolosalvatori** [comment]
Is there any way to eliminate the warning? It's very annoying, thanks

**Comment by Christina-Kang** [comment]
Thank you for the feedback, @paolosalvatori ! We can look into an option to suppress the warnings when explicitly requested. 

@suhuruli for visibility

**Comment by samedder** [comment]
The warning is meant to be annoying. It's also not coming from our CLI, but a warning from the underlying SSL library. It is meant to warn you. One option is to start securing your cluster with certificates that are trusted by the root CA bundle.
________________________________

**Comment by suhuruli** [comment]
There are two good pieces of feedback on this thread. 

1) @rganz, brought up a good point of having a message letting users know the connection was successful. 

2) @paolosalvatori, your point of getting rid of that warning is valid. Instead of spamming the user's terminal, we can just display the warning once and then not show it for future commands.
