### ISSUE TITLE
What is an example command for displaying the logs of my application/container?

### ISSUE THREAD

**Issue by drnic** [Azure/service-fabric-cli#75]
I'm new. I have deployed a silly public docker image that just prints to STDOUT every second. I'm trying to figure out how to see my SF container's logs. My searching of docs etc has failed me so I thought I'd create an issue - and perhaps I can take your answer and help write docs.

I think I understand `--node-name` (e.g. `_Node_1`) and `--application-id` (`sfctl application info --application-id Lattice` works), and `--service-manifest-name` (is it the `<Service Name="LatticeService">` from ApplicationManifest.xml?) but am unsure about `--code-package-name`.

e.g. how close am I?

```
sfctl service get-container-logs --node-name _Node_1 --application-id Lattice --service-manifest-name LatticeService --code-package-name ???
```

This errors with:

```
azure.servicefabric.models.fabric_error.FabricErrorException: (FABRIC_E_CONTAINER_NOT_FOUND) Container not found.
```

- [x] `sfctl` version, can check this using `pip show sfctl`
    Version: 4.0.0
- [x] Service Fabric cluster runtime version
    OSS servicefabric_6.2.141.1.deb
- [x] Service Fabric hosting location (on-premise or Azure usually)
    Self-hosted on AWS Ubuntu 16.04

**Comment by roshanroutray** [comment]
Please refer https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-and-service-manifests

`--node-name` and `--application-id` look fine

`--service-manifest-name` its <ServiceManifestRef ServiceManifestName="LatticeServicePkg" from ApplicationManifest.xml
`--code-package-name` its <CodePackage Name="Code" from ServiceManifest.xml

example:
> sfctl service get-container-logs --node-name _Node_1 --application-id Lattice --service-manifest-name LatticeServicePkg --code-package-name Code
