### ISSUE TITLE
sfctl application delete error: argument --force-remove expected one argument

### ISSUE THREAD

**Issue by talarari** [Azure/service-fabric-cli#77]
getting this error when trying to delete an app:
sfctl delete application --application-id fabric:/myapp --force-remove.

this shows up on the help menu but look like its not supported? i looked up force-remove in this repo and didn't find anything.

**Comment by Christina-Kang** [comment]
Using `--force-remove=true` should fix the issue. We will look into making this more explicit in the future :)
