### ISSUE TITLE
Error Installing Example Service

### ISSUE THREAD

**Issue by fizxmike** [Azure/service-fabric-cli#81]
After setting up Linux development environment for [Service Fabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux), [.NET Core](https://www.microsoft.com/net/learn/get-started/linux/ubuntu16-04) and [sfctl](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cli#ubuntu-and-windows-subsystem-for-linux).

I build an Azure Sample of a Service Fabric service and run the install script from here:
https://github.com/Azure-Samples/service-fabric-dotnet-core-getting-started/blob/master/Services/CounterService/install.sh

And I get the following error:
![image](https://user-images.githubusercontent.com/4626398/38460200-c952f284-3a7a-11e8-8613-222a5ec7c917.png)

Which points to this line in your code:
https://github.com/Azure/service-fabric-cli/blob/6ec1b1c8445b7cc5a889f3b172b47a6017c8888c/src/sfctl/custom_app.py#L100

Please advise, I'd like to get this example working.

**Comment by fizxmike** [comment]
If instead I use [this script](https://github.com/Azure/service-fabric-scripts-and-templates/blob/master/scripts/SetupServiceFabric/SetupServiceFabric.sh) to install Service Fabric and sfctl, I still get an error, but it's slightly different:
![image](https://user-images.githubusercontent.com/4626398/38460779-7fb10b1e-3a86-11e8-9bb3-5f33a24c4ee2.png)

**Comment by Christina-Kang** [comment]
Hi fizxmike,

Did you run `sfctl cluster select --endpoint=<your-endpoint>` before running install.sh?

If not, can you run that and see if the error is still occurring? 
If so, can you share the version of sfctl you have installed?

Thanks!

**Comment by fizxmike** [comment]
Yes! `sfctl cluster select --endpoint="http://localhost:19080"` enabled me to install the service. However, now I'm stuck with the ambiguous "Partition is below target replica or instance count." error:
![image](https://user-images.githubusercontent.com/4626398/39285211-c8fb4afa-48dc-11e8-9924-a5266e930cb6.png)
... but this is not a sfctl issue. (But if anyone could point me in the right direction, that would be great)
