### ISSUE TITLE
Add v4.0.0 whl to github release

### ISSUE THREAD

**Issue by drnic** [Azure/service-fabric-cli#94]
https://github.com/Azure/service-fabric-cli/releases/tag/v4.0.0 is missing the .whl file; it was included as part of https://github.com/Azure/service-fabric-cli/releases/tag/v3.0.0

**Comment by drnic** [comment]
Not critical at all; I just noticed it was added for v3.0.0 but missing from v4.0.0.

I can watch https://pypi.org/simple/sfctl/ using https://github.com/cf-platform-eng/concourse-pypi-resource if we're not going to add .whl to all github releases

**Comment by Christina-Kang** [comment]
Thanks for reporting the issue! :) https://github.com/Azure/service-fabric-cli/releases/tag/v4.0.0 now has the wheel file.
